### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by brianbroderick** [brianbroderick/pg_log_shipper#4]
```panic: runtime error: index out of range

goroutine 68 [running]:
main.extractComments(0xc4209dc3c0)
        /home/ubuntu/go/src/github.com/brianbroderick/pg_log_shipper/query.go:128 +0x266
main.newQuery(0xc420604000, 0x12a1, 0x12a1, 0xc420014600, 0x14, 0x12a1, 0x12a1, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/brianbroderick/pg_log_shipper/query.go:103 +0x525
main.getMultiLog(0xc420014600, 0x14, 0xc4208f7f00, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/brianbroderick/pg_log_shipper/redis.go:146 +0x476
main.startRedisBatch(0xc420014600, 0x14)
        /home/ubuntu/go/src/github.com/brianbroderick/pg_log_shipper/redis.go:60 +0x7c
created by main.main
        /home/ubuntu/go/src/github.com/brianbroderick/pg_log_shipper/main.go:60 +0x161```

**Comment by brianbroderick** [comment]
https://github.com/brianbroderick/pg_log_shipper/commit/fa85ed8c04025bb62b2ab5206ced5a1819ef79e3 

This seems to have fixed this error.
